<?php
// $Id$
require_once('general_deletion.inc');
require_once('email.inc');
/**
 * Implementation of hook_menu().
 */
function lab_migration_menu()
  {
    $items = array();
    /* PROPOSAL */
    $items['lab-migration/proposal'] = array(
        'title' => 'Lab Migration Proposal',
        'description' => 'Lab Migration Proposal',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_proposal_form'
        ),
        'access arguments' => array(
            'lab migration create proposal'
        ),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'proposal.inc'
    );
    $items['lab-migration/manage-proposal'] = array(
        'title' => 'LM Manage Lab Proposals',
        'description' => 'Manage Lab Migration Proposals',
        'page callback' => 'lab_migration_proposal_pending',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/pending'] = array(
        'title' => 'Pending Proposals',
        'description' => 'Pending Lab Migration Proposals Queue',
        'page callback' => 'lab_migration_proposal_pending',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/pending-solution-proposal'] = array(
        'title' => 'Pending Solution Proposals',
        'description' => 'Pending Lab Migration Solution Proposals Queue',
        'page callback' => 'lab_migration_solution_proposal_pending',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'manage_solution_proposal.inc'
    );
    $items['lab-migration/manage-proposal/pending-solution'] = array(
        'title' => 'Pending Solution',
        'description' => 'Pending Lab Migration Solution',
        'page callback' => 'lab_migration_proposal_pending_solution',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/all'] = array(
        'title' => 'All Proposals',
        'description' => 'All Proposals',
        'page callback' => 'lab_migration_proposal_all',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 4,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/category'] = array(
        'title' => 'Category',
        'description' => 'Category',
        'page callback' => 'lab_migration_category_all',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/category/edit'] = array(
        'title' => 'Edit Category',
        'description' => 'Edit category',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_category_edit_form'
        ),
        'access arguments' => array(
            'lab migration edit proposal'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/approve'] = array(
        'title' => 'Approve Proposal',
        'description' => 'Approve Proposal',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_proposal_approval_form'
        ),
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/solution-proposal-approve'] = array(
        'title' => 'Approve Solution Proposal',
        'description' => 'Approve Solution Proposal',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_solution_proposal_approval_form'
        ),
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'manage_solution_proposal.inc'
    );
    $items['lab-migration/manage-proposal/edit'] = array(
        'title' => 'Edit Proposal',
        'description' => 'Edit Proposal',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_proposal_edit_form'
        ),
        'access arguments' => array(
            'lab migration manage proposal'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'manage_proposal.inc'
    );
    $items['lab-migration/manage-proposal/status'] = array(
        'title' => 'Proposal Status',
        'description' => 'Proposal Status',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_proposal_status_form'
        ),
        'access arguments' => array(
            'lab migration approve proposal'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'manage_proposal.inc'
    );
    /* SOLUTION PROPOSAL */
    $items['lab-migration/open-proposal'] = array(
        'title' => 'Lab Migration Solve',
        'description' => 'Lab Migration Proposal Open For Solution',
        'page callback' => 'lab_migration_proposal_open',
        'access arguments' => array(
            'lab migration propose solution'
        ),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'solution_proposal.inc'
    );
    $items['lab-migration/show-proposal'] = array(
        'title' => 'Lab Migration Solution Proposal',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_solution_proposal_form'
        ),
        'access arguments' => array(
            'lab migration propose solution'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'solution_proposal.inc'
    );
    /* CODE REVIEW */
    $items['lab-migration/code-approval'] = array(
        'title' => 'LM Manage Code Approval',
        'description' => 'Manage Code Approval',
        'page callback' => 'lab_migration_code_approval',
        'access arguments' => array(
            'lab migration approve code'
        ),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'code_approval.inc'
    );
    $items['lab-migration/code-approval/approve'] = array(
        'title' => 'Code Approval',
        'description' => 'Code Approval',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_code_approval_form'
        ),
        'access arguments' => array(
            'lab migration approve code'
        ),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
        'file' => 'code_approval.inc'
    );
    $items['lab-migration/code-approval/bulk'] = array(
        'title' => 'Bulk Manage',
        'description' => 'Bulk Mangage',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_bulk_approval_form'
        ),
        'access arguments' => array(
            'lab migration bulk manage code'
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'bulk_approval.inc'
    );
    $items['lab-migration/code-approval/bulk'] = array(
        'title' => 'Bulk Manage',
        'description' => 'Bulk Mangage',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_bulk_approval_form'
        ),
        'access arguments' => array(
            'lab migration bulk manage code'
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'bulk_approval.inc'
    );
    /*$items['lab_migration/code_approval/dependency'] = array(
    'title' => 'Dependency',
    'description' => 'Dependency Mangage',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lab_migration_dependency_approval_form'),
    'access arguments' => array('lab migration bulk manage code'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'file' => 'dependency_approval.inc',
    );*/
    $items['lab-migration/code-approval/upload'] = array(
        'title' => 'Upload Code',
        'description' => 'Admin Upload',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_bulk_upload_code_form'
        ),
        'access arguments' => array(
            'lab migration bulk manage code'
        ),
        'type' => MENU_CALLBACK,
        'weight' => 4,
        'file' => 'bulk_upload_code.inc'
    );
    $items['lab-migration/code-approval/notes'] = array(
        'title' => 'Notes for Reviewers',
        'description' => 'Notes for Reviewers',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_lab_notes_form'
        ),
        'access arguments' => array(
            'lab migration bulk manage code'
        ),
        'type' => MENU_CALLBACK,
        'weight' => 4,
        'file' => 'notes.inc'
    );
    /* CODE UPLOAD */
    $items['lab-migration/code'] = array(
        'title' => 'Code Submission',
        'description' => 'Code Submission',
        'page callback' => 'lab_migration_list_experiments',
        'access callback' => 'user_access',
        'access arguments' => array(
            'lab migration upload code'
        ),
        'file' => 'upload_code.inc'
    );
    $items['lab-migration/code/list-experiments'] = array(
        'title' => 'List Experiments',
        'description' => 'List Experiments',
        'page callback' => 'lab_migration_list_experiments',
        'access arguments' => array(
            'lab migration upload code'
        ),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'file' => 'upload_code.inc',
        'weight' => 1
    );
    $items['lab-migration/code/upload'] = array(
        'title' => 'Code Submission',
        'description' => 'Code Submission',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_upload_code_form'
        ),
        'access arguments' => array(
            'lab migration upload code'
        ),
        'type' => MENU_LOCAL_TASK,
        'file' => 'upload_code.inc',
        'weight' => 2
    );
    /* $items['lab_migration/code/upload_dep'] = array(
    'title' => 'Upload Dependency',
    'description' => 'Upload Dependency Files',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lab_migration_upload_dependency_form'),
    'access arguments' => array('lab migration upload code'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dependency.inc',
    'weight' => 3,
    );*/
    $items['lab-migration/code/delete'] = array(
        'title' => 'Delete Solution',
        'description' => 'Delete Solution',
        'page callback' => 'lab_migration_upload_code_delete',
        'access arguments' => array(
            'lab migration upload code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'upload_code_delete.inc'
    );
    /* CODE DOWNLOADS */
    $items['lab-migration/download/file'] = array(
        'title' => 'Code Download',
        'description' => 'Code Download',
        'page callback' => 'lab_migration_download_solution_file',
        'access arguments' => array(
            'lab migration download code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'download.inc'
    );
    /*$items['lab_migration/download/dependency'] = array(
    'title' => 'Code Download',
    'description' => 'Code Download', 
    'page callback' => 'lab_migration_download_dependency_file',
    'access arguments' => array('lab migration download code'),
    'type' => MENU_CALLBACK,
    'file' => 'download.inc',
    );*/
    $items['lab-migration/download/solution'] = array(
        'title' => 'Code Download',
        'description' => 'Code Download',
        'page callback' => 'lab_migration_download_solution',
        'access arguments' => array(
            'lab migration download code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'download.inc'
    );
    $items['lab-migration/download/experiment'] = array(
        'title' => 'Code Download',
        'description' => 'Code Download',
        'page callback' => 'lab_migration_download_experiment',
        'access arguments' => array(
            'lab migration download code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'download.inc'
    );
    $items['lab-migration/download/lab'] = array(
        'title' => 'Code Download',
        'description' => 'Code Download',
        'page callback' => 'lab_migration_download_lab',
        'access arguments' => array(
            'lab migration download code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'download.inc'
    );
    $items['lab-migration/full-download/experiment'] = array(
        'title' => 'Code Download',
        'description' => 'Code Download',
        'page callback' => 'lab_migration_download_full_experiment',
        'access arguments' => array(
            'lab migration approve code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'full_download.inc'
    );
    $items['lab-migration/full-download/lab'] = array(
        'title' => 'Code Download',
        'description' => 'Code Download',
        'page callback' => 'lab_migration_download_full_lab',
        'access arguments' => array(
            'lab migration approve code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'full_download.inc'
    );
    /* COMPLETED LAB MIGRATIONS */
    $items['lab-migration/completed-labs'] = array(
        'title' => 'Completed Labs',
        'page callback' => 'lab_migration_completed_labs_all',
        'access arguments' => array(
            'lab migration download code'
        ),
        'file' => 'lab_details.inc'
    );
    /* LABS IN PROGRESS */
    $items['lab-migration/labs-progress'] = array(
        'title' => 'Labs in Progress',
        'page callback' => 'lab_migration_labs_progress_all',
        'access arguments' => array(
            'lab migration download code'
        ),
        'file' => 'lab_details.inc'
    );
    /* DOWNLOAD FOR EVERYONE */
    $items['lab-migration/lab-migration-run'] = array(
        'title' => 'Download Codes',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_run_form'
        ),
        'access arguments' => array(
            'lab migration download code'
        ),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'run.inc'
    );
    /*$items['lab_migration_run'] = array(
    'title' => 'Download Codes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lab_migration_run_form_ajax'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'run.inc',
    );
    $items['lab_migration_run_ajax'] = array(
    'page callback' => 'lab_migration_run_ajax',
    'access callback' => TRUE,
    'file' => 'run.inc',
    );
    $items['download_codes'] = array(
    'title' => 'Download Codes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lab_migration_run_form_ajax'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'run.inc',
    );*/
    /* LATEX SCRIPT */
    $items['lab-migration/generate-lab'] = array(
        'title' => 'Generate Lab',
        'description' => 'Generate Lab From Latex Script',
        'page callback' => 'lab_migration_download_lab_pdf',
        'access arguments' => array(
            'lab migration generate lab'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'latex.inc'
    );
    $items['lab-migration/delete-lab'] = array(
        'title' => 'Delete Lab PDF',
        'description' => 'Delete Lab PDF',
        'page callback' => 'lab_migration_delete_lab_pdf',
        'access arguments' => array(
            'lab migration approve code'
        ),
        'type' => MENU_CALLBACK,
        'file' => 'latex.inc'
    );
    /* ADMIN SETTINGS */
    $items['admin/settings/lab-migration'] = array(
        'title' => 'Lab Migration Settings',
        'description' => 'Lab Migration Settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'lab_migration_settings_form'
        ),
        'access arguments' => array(
            'administer lab migration'
        ),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'settings.inc'
    );
    /* AJAX REQUEST */
    $items["lab-bulk-manage-exp/ajax"] = array(
        "title" => "Ajax callbacks",
        "page callback" => "lab_bulk_manage_exp_ajax",
        "access arguments" => array(
            "lab migration bulk manage code"
        ),
        "type" => MENU_CALLBACK,
        'file' => 'bulk_approval.inc'
    );
    /*  $items["lab_migration/code_approval/dependency/ajax"] = array(
    "title" => "Ajax callbacks",
    "page callback" => "lab_migration_dependency_approval_ajax",
    "access arguments" => array("lab migration bulk manage code"),
    "type" => MENU_CALLBACK,
    'file' => 'dependency_approval.inc',
    );*/
    return $items;
  }
/**
 * Implementation of hook_perm().
 */
function lab_migration_permission()
  {
    return array(
        'lab migration create proposal' => array(
            'title' => t('lab migration create proposal'),
            'restrict access' => TRUE
        ),
        'lab migration manage proposal' => array(
            'title' => t('lab migration manage proposal'),
            'restrict access' => TRUE
        ),
        'lab migration edit proposal' => array(
            'title' => t('lab migration edit proposal'),
            'restrict access' => TRUE
        ),
        'lab migration approve proposal' => array(
            'title' => t('lab migration approve proposal'),
            'restrict access' => TRUE
        ),
        'lab migration propose solution' => array(
            'title' => t('lab migration propose solution'),
            'restrict access' => TRUE
        ),
        'lab migration approve code' => array(
            'title' => t('lab migration approve code'),
            'restrict access' => TRUE
        ),
        'lab migration bulk manage code' => array(
            'title' => t('lab migration bulk manage code'),
            'restrict access' => TRUE
        ),
        'lab migration bulk delete code' => array(
            'title' => t('lab migration bulk delete code'),
            'restrict access' => TRUE
        ),
        'lab migration upload code' => array(
            'title' => t('lab migration upload code'),
            'restrict access' => TRUE
        ),
        'lab migration download code' => array(
            'title' => t('lab migration download code'),
            'restrict access' => TRUE
        ),
        'administer lab migration' => array(
            'title' => t('administer lab migration'),
            'restrict access' => TRUE
        ),
        'lab migration generate lab' => array(
            'title' => t('lab migration generate lab'),
            'restrict access' => TRUE
        )
    );
    // return array('lab migration create proposal', 'lab migration manage proposal', 'lab migration edit proposal', 'lab migration approve proposal', 'lab migration propose solution', 'lab migration approve code', 'lab migration bulk manage code', 'lab migration bulk delete code', 'lab migration upload code', 'lab migration download code', 'administer lab migration', 'lab migration generate lab');
  }
/* AJAX CALLS */
function lab_migration_ajax()
  {
    $query_type = arg(2);
    if ($query_type == 'chapter_title')
      {
        $chapter_number = arg(3);
        $preference_id = arg(4);
        //$chapter_q = db_query("SELECT * FROM {lab_migration_chapter} WHERE number = %d AND preference_id = %d LIMIT 1", $chapter_number, $preference_id);
        $query = db_select('lab_migration_chapter');
        $query->fields('lab_migration_chapter');
        $query->condition('number', $chapter_number);
        $query->condition('preference_id', $preference_id);
        $query->range(0, 1);
        $chapter_q = $query->execute();
        if ($chapter_data = $chapter_q->fetchObject())
          {
            echo $chapter_data->name;
            return;
          }
      }
    else if ($query_type == 'example_exists')
      {
        $chapter_number = arg(3);
        $preference_id = arg(4);
        $example_number = arg(5);
        $chapter_id = 0;
        $query = db_select('lab_migration_chapter');
        $query->fields('lab_migration_chapter');
        $query->condition('number', $chapter_number);
        $query->condition('preference_id', $preference_id);
        $query->range(0, 1);
        $chapter_q = $query->execute();
        if (!$chapter_data = $chapter_q->fetchObject())
          {
            echo '';
            return;
          }
        else
          {
            $chapter_id = $chapter_data->id;
          }
        $query = db_select('lab_migration_example');
        $query->fields('lab_migration_example');
        $query->condition('chapter_id', $chapter_id);
        $query->condition('number', $example_number);
        $query->range(0, 1);
        $example_q = $query->execute();
        if ($example_data = $example_q->fetchObject())
          {
            if ($example_data->approval_status == 1)
                echo 'Warning! Solution already approved. You cannot upload the same solution again.';
            else
                echo 'Warning! Solution already uploaded. Delete the solution and reupload it.';
            return;
          }
      }
    echo '';
  }
/*************************** VALIDATION FUNCTIONS *****************************/
function lab_migration_check_valid_filename($file_name)
  {
    if (!preg_match('/^[0-9a-zA-Z\.]+$/', $file_name))
        return FALSE;
    else if (substr_count($file_name, ".") > 1)
        return FALSE;
    else
        return TRUE;
  }
function lab_migration_check_name($name = '')
  {
    if (!preg_match('/^[0-9a-zA-Z\ ]+$/', $name))
        return FALSE;
    else
        return TRUE;
  }
function lab_migration_check_code_number($number = '')
  {
    if (!preg_match('/^[0-9]+$/', $number))
        return FALSE;
    else
        return TRUE;
  }
function lab_migration_path()
  {
    return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'r_uploads/lab_migration_uploads/';
  }
/************************* USER VERIFICATION FUNCTIONS ************************/
function lab_migration_get_proposal()
  {
    global $user;
    //$proposal_q = db_query("SELECT * FROM {lab_migration_proposal} WHERE solution_provider_uid = ".$user->uid." AND solution_status = 2 ORDER BY id DESC LIMIT 1");
    $query = db_select('lab_migration_proposal');
    $query->fields('lab_migration_proposal');
    $query->condition('solution_provider_uid', $user->uid);
    $query->condition('solution_status', 2);
    $query->orderBy('id', 'DESC');
    $query->range(0, 1);
    $proposal_q = $query->execute();
    $proposal_data = $proposal_q->fetchObject();
    if (!$proposal_data)
      {
        drupal_set_message("You do not have any approved Lab migraion solution proposal. Please check the " . l('available', 'lab-migration/open-proposal') . " Lab migration proposal.", 'error');
        drupal_goto('');
      }
    switch ($proposal_data->approval_status)
    {
        case 0:
            drupal_set_message(t('Proposal is awaiting approval.'), 'status');
            return FALSE;
        case 1:
            return $proposal_data;
        case 2:
            drupal_set_message(t('Proposal has been dis-approved.'), 'error');
            return FALSE;
        case 3:
            drupal_set_message(t('Proposal has been marked as completed.'), 'status');
            return FALSE;
        default:
            drupal_set_message(t('Invalid proposal state. Please contact site administrator for further information.'), 'error');
            return FALSE;
    }
    return FALSE;
  }
/***************************** GENERAL FUNCTIONS ******************************/
function lab_migration_get_category_name($category_id)
  {
    $category_data = '';
    switch ($category_id)
    {
        case 0:
            $category_data = 'Not Selected';
            break;
        case 1:
            $category_data = 'Fluid Mechanics';
            break;
        case 2:
            $category_data = 'Control Theory & Control Systems';
            break;
        case 3:
            $category_data = 'Chemical Engineering';
            break;
        case 4:
            $category_data = 'Thermodynamics';
            break;
        case 5:
            $category_data = 'Mechanical Engineering';
            break;
        case 6:
            $category_data = 'Signal Processing';
            break;
        case 7:
            $category_data = 'Digital Communications';
            break;
        case 8:
            $category_data = 'Electrical Technology';
            break;
        case 9:
            $category_data = 'Mathematics & Pure Science';
            break;
        case 10:
            $category_data = 'Analog Electronics';
            break;
        case 11:
            $category_data = 'Digital Electronics';
            break;
        case 12:
            $category_data = 'Computer Programming';
            break;
        case 13:
            $category_data = 'Others';
            break;
        default:
            $category_data = 'Unknown';
            break;
    }
    return $category_data;
  }
/*function lab_migration_init() {

drupal_add_js(drupal_get_path('module', 'lab_migration') . '/js/lab_migration_ajax.js', array ('scope' => 'footer'));
}*/
/*************************************************************************/
/***** Function To convert only first charater of string in uppercase ****/
/*************************************************************************/
function lm_ucname($string)
  {
    $string = ucwords(strtolower($string));
    foreach (array(
        '-',
        '\''
    ) as $delimiter)
      {
        if (strpos($string, $delimiter) !== false)
          {
            $string = implode($delimiter, array_map('ucfirst', explode($delimiter, $string)));
          }
      }
    return $string;
  }
 
 function _lm_list_of_states()
  {
    $states = array(0 => '-Select-');
    $query = db_select('list_states_of_india');
    $query->fields('list_states_of_india');
    //$query->orderBy('', '');
    $states_list = $query->execute();
    while ($states_list_data = $states_list->fetchObject())
      {
        $states[$states_list_data->state] = $states_list_data->state;
      }
    return $states;
  }

  
function _lm_list_of_cities()
  {
    $city = array(0 => '-Select-');
    $query = db_select('list_cities_of_india');
    $query->fields('list_cities_of_india');
    $query->orderBy('city', 'ASC');
    $city_list = $query->execute();
    while ($city_list_data = $city_list->fetchObject())
      {
        $city[$city_list_data->city] = $city_list_data->city;
      }
    return $city;
  }
function _lm_list_of_departments()
  {
    $department = array();
    $query = db_select('list_of_departments');
    $query->fields('list_of_departments');
    $query->orderBy('id', 'DESC');
    $department_list = $query->execute();
    while ($department_list_data = $department_list->fetchObject())
      {
        $department[$department_list_data->department] = $department_list_data->department;
      }
    return $department;
  }
function _lm_list_of_software_version()
  {
    $software_version = array();
    $query = db_select('r_software_version');
    $query->fields('r_software_version');
    $query->orderBy('id', 'DESC');
    $software_version_list = $query->execute();
    while ($software_version_list_data = $software_version_list->fetchObject())
      {
        $software_version[$software_version_list_data->r_version] = $software_version_list_data->r_version;
      }
    return $software_version;
  }
 
 
