lab_migration.settings:
  type: mapping
  label: Settings
  mapping:
    lab_migration_from_email:
      type: 'NULL'
    lab_migration_emails:
      type: string
    lab_migration_cc_emails:
      type: string
    lab_migration_source_extensions:
      type: string
    lab_migration_result_extensions:
      type: string
    lab_migration_xcos_extensions:
      type: string
    lab_migration_dependency_extensions:
      type: string
    lab_migration_pdf_extensions:
      type: string
    lab_migration_syllabus_file_extensions:
      type: string
